package walletrpc

type VerifyRequest struct {
	// Data What should have been signed.
	Data string `json:"data"`

	// Address Public address of the wallet used to sign the data.
	Address string `json:"address"`

	// Signature signature generated by sign method.
	Signature string `json:"signature"`
}

type VerifyResponse struct {
	Good bool `json:"good"`
}

// Verify Verify a signature on a string.
func (c *Client) Verify(req *VerifyRequest) (*VerifyResponse, error) {
	resp := &VerifyResponse{}
	err := c.do("verify", &req, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
